### ISSUE TITLE
Providing public API and SDKs?

### ISSUE THREAD

**Issue by imdreamrunner** [idf/tagr#1]

**Comment by idf** [comment]
Post the text to URL /, {text: "text"}, response is {keywords: ["pharse1", "phrase2"]}. Enjoy!

**Comment by imdreamrunner** [comment]
add a document!
ask app to reg and use app-id and app-secret.
charge by usage!
i only charge 20% from your income through this idea

**Comment by idf** [comment]
授人以渔不如授人以云端渔。good call
